sudo: false
language: node_js
node_js:
- '6'
env:
  global:
  - BROWSERSTACK_USERNAME: dtktestaccount1
  - BROWSERSTACK_ACCESS_KEY: mG2qbEFJCZY2qLsM7yfx
  - SAUCE_USERNAME: dojo2-ts-ci
  - SAUCE_ACCESS_KEY: e92610e3-834e-4bec-a3b5-6f7b9d874601
cache:
  directories:
  - node_modules
install:
- travis_retry npm install grunt-cli
- travis_retry npm install
script:
- grunt
- grunt intern:node --combined
- grunt intern:saucelabs --combined
- grunt remapIstanbul:ci
- grunt uploadCoverage
notifications:
  slack:
    secure: BprehuYxgpg7PS5lpxIcWUXtI2GkAZmb+b9dgDEmpyliMMOj8CCNhhvnyr3tdZBH0VFK5eej1fFRAY6yXz/CBMbx+fbVzDkWFdS6HtadX4o9beiFUUx1vRF38wCcfMJjZdO8pHA4PP4Dz/Honf685ZD/M6lSUZcsy8w2auo2iCJCSBZivc5KEOo2VKcQdrjUDpESKvGthi0NqWymY2/HLtJe/QvLZzzLn6ycd/2Qm0lha7HpkBUnIJ+hJHYPB/BVxziyyhzEj2wm15ifTPaPjDVlePoESXuESQ5pfS9OJBYXrGbsZH84yMN94l2NCdFuTkfdMjK9fXrGeLy6YanHzsG1vnYABsY1kePuOU3E0KlrfJHv/XeSnmf+6rMWUxMy7x9PtCVf/TE5nNkjiIODRhI0FadE/kI7FiyLMGT8hhzV0NGnZEer0I7rHMkI9t6fYHa+KwLIOtcZ4hc23lkCwG1jYkX8iqBiu7ls3rkNH5zn9DE1+Kzw03qmKT6LhVAWoGxwmswdGSg246MiJExhCVY0wpKgAQkpkeCubd+2wHDk4kx+Z7ky7642tXk/diDJbiBVmn9nqomwVvYecWGdR9eiKLXQ6Ln/URZRuNe4XjZTJ0YdNhLXD3kI0gggJ+jfCMHQF3JS1fHhLVPR1HpADOFUxBOYaJn/p4l6ceKGLNY=
